# Generated by Django 4.2.6 on 2023-10-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_remove_contact_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lname',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
